### ISSUE TITLE
https://docs.cyclic.sh/overview/starters  is not reachable .

### ISSUE THREAD

**Issue by sahilbakoru** [cyclic-software/docs#135]
https://docs.cyclic.sh/overview/starters is not reachable screen shot is added below .
![Screenshot 2024-05-31 at 6 04 30 AM](https://github.com/cyclic-software/docs/assets/68190549/1e0f6b05-ae4d-4273-afc7-45a9356c270b)

**Comment by TijanAyo** [comment]
The reason might be that cyclic is shutting down its service check out their blog post [here](https://www.cyclic.sh/posts/cyclic-is-shutting-down/)

**Comment by sahilbakoru** [comment]
@TijanAyo thank you !
