### ISSUE TITLE
Website broken endpoints

### ISSUE THREAD

**Issue by harshgupta20** [cyclic-software/docs#137]
I tried navigating throughout the website as found login and docs are not reachable.
![as](https://github.com/cyclic-software/docs/assets/59175412/b0b3e327-8471-40b6-ae56-0bee2b2ed400)

**Comment by TijanAyo** [comment]
> I tried navigating throughout the website as found login and docs are not reachable. ![as](https://private-user-images.githubusercontent.com/59175412/344757607-b0b3e327-8471-40b6-ae56-0bee2b2ed400.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTQxMDAsIm5iZiI6MTcxOTg5MzgwMCwicGF0aCI6Ii81OTE3NTQxMi8zNDQ3NTc2MDctYjBiM2UzMjctODQ3MS00MGI2LWFlNTYtMGJlZTJiMmVkNDAwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA0MTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MzFmNTRjYWZkYTZkMjUwMWQxMGIzYzkzYThlNjNiMGYwZjY3MDgxOTc1MTJlZDcxMTlhYjMwYmEyNWIwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIpthCtm2ZjnxBruWTRZr0fuRNWotSAXQFg3On9fkvI)

That might be because cyclic is shutting down, they wrote about it [here](https://www.cyclic.sh/posts/cyclic-is-shutting-down/)
