### ISSUE TITLE
stop.

### ISSUE THREAD

**Issue by ndzn** [cyclic-software/docs#40]
stop spamming emails that make 0 context, look, if you want users for your app, scraping github and emailing people because of using a certain framework in a repo is not the way to do it. leaves a bad taste in peoples mouth. just stop

if you're using this service, just be aware they spam email at random from @cyclic.sh to get users, scummy business model to get users

**Comment by korostelevm** [comment]
Hey @frinned, sorry if we didn't get the context right. We do find relevant users on GitHub by searching dependencies. Getting the word out about a new platform isn't easy but we've had a good experience engaging with devs like us on github. Would love to get your input on how to do a better job reaching out.

We only email public emails and never automatically. 
Nice email domain btw (I picked up `ha.wtf` myself)
