### ISSUE TITLE
404 Error While Editing A Page on doc.cyclic.sh

### ISSUE THREAD

**Issue by Ayushparui** [cyclic-software/docs#49]
I was trying to remove a word from the doc but it seems there's an error when it redirects to another GitHub Webpage.  ([Link](https://github.com/cyclic-software/docs/edit/main/website/docs/overview/launch.md))

**Comment by seekayel** [comment]
@Ayushparui on what page are you seeing that link? I think this is the markdown file you are trying to edit? (https://github.com/cyclic-software/docs/blob/main/docs/overview/launch.md)

PRs welcomed! Thanks.

**Comment by seekayel** [comment]
@Ayushparui figured it out. Thanks for the report!
