### ISSUE TITLE
Any way to select branch of repo?

### ISSUE THREAD

**Issue by iuliuvisovan** [cyclic-software/docs#66]
Hey, according to docs, `New deployments will be triggered automatically on code changes to the default branch of the repo`. 

However my target code is in the `staging` branch of the repository. Any way I can tell Cyclic to use that for deploys?

Thanks

**Comment by seekayel** [comment]
Once deployed goto the dashboard, select your app and then: `Environments` > `Auto-Deployments` > `Branch Name`
