### ISSUE TITLE
Deploy hangs on empty Repo

### ISSUE THREAD

**Issue by P-Copley** [cyclic-software/docs#76]
I recently tried to a link an empty repo by accident. This just caused it to hang with a 500 error in the console. 

This is obviously user error but just leaving this here in case you weren't aware. Feel free to close if this isn't where you'd like feedback.

**Comment by seekayel** [comment]
Was this a newly created repo or a repo that was created but with no files?

Best to report in our discord if you want support (sounds like you are good?) https://discord.cyclic.sh/support
