### ISSUE TITLE
Suddenly all apps got ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Zipexpo** [cyclic-software/docs#96]
I got the issue with HTTPS. It is not happened before (at least 2 weeks ago) but now all my apps got the SSL error
e.g: https://dead-lime-barnacle-tie.cyclic.app/

![image](https://user-images.githubusercontent.com/18387748/227696321-9797ab67-e37f-4370-9b30-f6c54a8ff0d3.png)

**Comment by DanielMiao1** [comment]
Hi,
I can't reproduce the issue with the website on my computer (see screenshots section).
If the same issue still happens, maybe you could try clearing the browser cache (or force reloading the page `Ctrl-Shift-R`) and/or trying on a different browser/computer.

<details>
<summary>Screenshots</summary>

<img width="1920" alt="Screenshot 2023-03-25 at 6 07 13 PM" src="https://user-images.githubusercontent.com/83146190/227749989-309fc7b5-818f-4487-a038-f4a5fddfb2d1.png">
<img width="3360" alt="Screenshot 2023-03-25 at 5 42 30 PM" src="https://user-images.githubusercontent.com/83146190/227749993-a912b236-e75f-4575-a368-eeed758508d4.png">
<img width="3360" alt="Screenshot 2023-03-25 at 5 42 53 PM" src="https://user-images.githubusercontent.com/83146190/227749999-36ad9516-7b0c-48f3-8752-51d786251da4.png">


</details>

**Comment by seekayel** [comment]
I am not able to reproduce either through curl or chrome on my Mac laptop.

Here is my curl output showing SSL cert worked:
```
$ curl -v https://dead-lime-barnacle-tie.cyclic.app/
*   Trying 52.5.197.179:443...
* Connected to dead-lime-barnacle-tie.cyclic.app (52.5.197.179) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.cyclic.app
*  start date: Feb 27 00:00:00 2023 GMT
*  expire date: Oct 29 23:59:59 2023 GMT
*  subjectAltName: host "dead-lime-barnacle-tie.cyclic.app" matched cert's "*.cyclic.app"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
```


@Zipexpo:
- what version of chrome on what platform?
- what is the output of `curl -v https://dead-lime-barnacle-tie.cyclic.app/`?

**Comment by Zipexpo** [comment]
Thank you for replying,
I forgot to mention that I don't use Mac but Win 11.
I also test to access it with my phone (Samsung note 10) on the Samsung Internet app but failed as well with the same reason.

The result from curl comand on my WIn 11

```
curl -v https://dead-lime-barnacle-tie.cyclic.app/
*   Trying 167.206.37.137:443...
* Connected to dead-lime-barnacle-tie.cyclic.app (167.206.37.137) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
* Closing connection 0
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
```

I would recommend you test with a VM or on the smartphone (maybe android)

**Comment by seekayel** [comment]
We are researching. We are seeing incorrect certs getting returned. We have escalated the issue and are discussing different ways to fix. Will keep you posted.

**Comment by Zipexpo** [comment]
Hi,
I'd like to know if you did something because the web apps are back to normal.
If you are done with testing, please close this issue.
I appreciate your support.

**Comment by seekayel** [comment]
No fix on our side. The research/escalation with AWS may have led them to change/update something. However I don't have confirmation of that right now. Lets leave this open for now.
